version: '2'
services:
    tool:
        image: macintoshplus/php:php72
        volumes:
            - ./:/sources
            - /var/www:/var/www
            - /home/jbnahan/.config/composer/vendor/bin/composer:/usr/local/bin/composer
        dns:
            - 8.8.8.8
